In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
df=df.drop(labels="alive",axis=1)
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town  alone  
0    man        True  NaN  Southampton  False  
1  woman       False    C    Cherbourg  False  
2  woman       False  NaN  Southampton   True  
3  woman       False    C  Southampton  False  
4    man        True  NaN  Southampton   True

In [4]:
df = df[["sex","embarked","alone","pclass","survived"]]

In [5]:
df.head()

sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

In [6]:
import numpy as np
df['sex']=np.where(df['sex']=="male",1,0)

In [7]:
df.head()

sex embarked  alone  pclass  survived
0    1        S  False       3         0
1    0        C  False       1         1
2    0        S   True       3         1
3    0        S  False       1         1
4    1        S   True       3         0

In [8]:
print(df["embarked"].unique())

['S' 'C' 'Q' nan]


In [9]:
import numpy as np 
ordinal_label = {k: i for i, k in enumerate(df['embarked'].unique(), 0)}

In [10]:
ordinal_label

{'S': 0, 'C': 1, 'Q': 2, nan: 3}

In [11]:
df["embarked"]=df["embarked"].map(ordinal_label)
df.head()

sex  embarked  alone  pclass  survived
0    1         0  False       3         0
1    0         1  False       1         1
2    0         0   True       3         1
3    0         0  False       1         1
4    1         0   True       3         0

In [12]:
df["alone"]=np.where(df["alone"]==True,1,0)
df.head()

sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

In [13]:
X = df.drop(labels="survived",axis=1)
Y = df["survived"]

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=0,test_size=0.3)

In [15]:
X_train.head()

sex  embarked  alone  pclass
857    1         0      1       1
52     0         1      0       1
386    1         0      0       3
124    1         0      0       1
578    0         1      0       3

In [16]:
Y_train.head()

857    1
52     1
386    0
124    0
578    0
Name: survived, dtype: int64

In [17]:
X_train.isnull().sum()


sex         0
embarked    0
alone       0
pclass      0
dtype: int64

In [18]:
from sklearn.feature_selection import chi2
f_p_values = chi2(X_train,Y_train)
f_p_values

(array([63.55447864, 11.83961845,  9.03328564, 21.61080949]),
 array([1.55992554e-15, 5.79837058e-04, 2.65107556e-03, 3.33964360e-06]))

In [19]:
f_p_values[1]

array([1.55992554e-15, 5.79837058e-04, 2.65107556e-03, 3.33964360e-06])

In [20]:
import pandas as pd
data_frame = pd.Series(f_p_values[1])
data_frame.index=X_train.columns
data_frame.sort_index(ascending=False)

sex         1.559926e-15
pclass      3.339644e-06
embarked    5.798371e-04
alone       2.651076e-03
dtype: float64

# Observation


Sex Column is the most important column when compared to the output feature Survived